apiVersion: v1
kind: ConfigMap
metadata:
  name: aggregator-config
data:
  application.properties: |
    spring.application.name=aggregator-microservice
    clients.humidity-service-url=http://humidity-service/humidity
    clients.temperature-service-url=http://temperature-service/temperature
    temperature-unit.unit=celsius
